version: "3.3"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: espe
      POSTGRES_PASSWORD: espe
      POSTGRES_DB: GERDB
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: espe@gmail.com
      PGADMIN_DEFAULT_PASSWORD: espe